# Generated by Django 2.1.5 on 2019-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190115_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
